[package]
name = "tsls"
version = "0.1.0"
authors = ["tennashi <yuya.gt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
